# Generated by Django 2.2.19 on 2021-03-22 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('myproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mywatchlist', to='auctions.Auction')),
            ],
        ),
    ]
