# Generated by Django 2.2.19 on 2021-03-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='myWatchlist', to='auctions.Auction'),
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
