# Generated by Django 2.2.19 on 2021-03-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210322_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='userWatchlist', to='auctions.Auction'),
        ),
    ]
